### PR TITLE
Maintainability

### LINKED ISSUE #8: chore: add .clang-format

### LINKED ISSUE #9: chore: add clang-tidy

### LINKED ISSUE #13: Convert changelog into markdown.
Switch from HTML to markdown. Convert the existing changelog.

### PR DESCRIPTION
**Pull request by carlocorradini**
Complete rewrite with new structure, features and more...
I've set minimum `CMake` version to 3.14 (following [`CPM`](https://github.com/cpm-cmake/CPM.cmake)) but should be decreased.
@karljj1 Let me know what you think 🥳🤯

NOTE: Currently this is a draft (unfinished)

Fix #8 
Fix #9
Fix #13

### CODE REVIEW

**Comment by karljj1** [comment]
Looks good. Are these just changes to the structure or are there also code changes? Github was struggling to show the PR so I couldn't review it all.

**Comment by carlocorradini** [comment]
The code is the same (it has only been formatted by clang-format).
The only changes I made are in KDefines.hpp but it should be refactored since we will use [`GenerateExportHeader`](https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html). Therefore the custom DLL export is deprecated/useless.
For the other changes etc... what do you think?

**Comment by karljj1** [comment]
> The code is the same (it has only been formatted by clang-format). The only changes I made are in KDefines.hpp but it should be refactored since we will use [`GenerateExportHeader`](https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html). Therefore the custom DLL export is deprecated/useless. For the other changes etc... what do you think?

Oh very nice. `GenerateExportHeader` looks great :)

**Comment by carlocorradini** [comment]
@karljj1 Note that you can edit (create commits and push them) to my branch since I've allowed edits from maintainers

**Comment by carlocorradini** [comment]
@karljj1 I think we have a pretty good starting point now.
What do you think?
Note that the CI/CD has been improved.
Added `GenerateExportHeader`.
You can release a new version of KDIS automatically by pushing a tag ([SEMVER](https://semver.org) compatible). E.g.: `v3.0.0`

**Comment by karljj1** [comment]
Looks great! Im happy to merge this in if you are. Thanks for all the hard work :)

**Review by karljj1 — APPROVED** [review]

**Comment by carlocorradini** [comment]
@karljj1 I think it's better if you release version `2.10.0` with the old code and structure (can you update the CHANGELOG.md file in my branch please).
Then, merge the PR (note that it's not finished yet) and update the CHANGELOG.md file in unreleased version (this will be 3.0.0).

**Comment by karljj1** [comment]
Thanks for the PR! Really appreciate all the work you did,

**Comment by carlocorradini** [comment]
Wow 😳 Thanks
The repo looks really good now 🥳
We need to update all the code and more 🥳👍

**Pull request merged**
